language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  - "pypy3"

install:
  - pip install tox-travis
  - pip install -r requirements-dev.txt
script:
  - flake8 . --ignore=E501,E402
  - tox
after_success:
  - coveralls
